# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-23 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20200817_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='书名'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='mubook',
        ),
    ]
