# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-23 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20200823_2107'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
